### ISSUE TITLE
Structure Angular App

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [muhammadawaisshaikh/community-events-angular#1]
1. Http API mechanism
2. Shared Module (shared components like search-bar, card etc.)
3. interceptors (Loader, Token)
4. Services
5. Constants
6. Guards
7. As good as you can

**Comment by haroon786** [comment]
![image](https://user-images.githubusercontent.com/20164301/135152452-b7507edc-cac8-45e8-94e9-9b6302e37244.png)
can you please check the folder structure or do we need to update something?

**Comment by muhammadawaisshaikh** [comment]
Nope it needs more work. Please do follow this app for now, with the matter of time we will evolve it accordingly.

https://github.com/muhammadawaisshaikh/mumm-app

**Comment by muhammadawaisshaikh** [comment]
Make components and services for now like in above app. Create sample services and known components like header footer and config service

**Comment by haroon786** [comment]
![image](https://user-images.githubusercontent.com/20164301/135157708-ade9e7d8-5752-4625-b9cd-f6f9a4a3a17c.png)

**Comment by muhammadawaisshaikh** [comment]
Can you please move the header, footer components in the layout directory? Once done with it, open a pull request and assign me as a reviewer. I will look into this thanks

**Comment by muhammadawaisshaikh** [comment]
done.
