### ISSUE TITLE
Create an Event Module with base component

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [muhammadawaisshaikh/community-events-angular#11]
- inside /modules > events module

Details: Create a base component for that module, which will hold a router-outlet for child components.

**Comment by kala2** [comment]
I'll take tis one, please assign to me

**Comment by muhammadawaisshaikh** [comment]
you are asking for all small works, however you have experience on angular :)

**Comment by muhammadawaisshaikh** [comment]
i want from you to work on any reusable listing component or some UI part if you can. thanks

**Comment by muhammadawaisshaikh** [comment]
i have assigned to you, enjoy.

**Comment by muhammadawaisshaikh** [comment]
@kala2 any update? are you going to work on this or not?

**Comment by kala2** [comment]
Yes i am working on it, I will submit a pr soon

**Comment by kala2** [comment]
Submitted #35 PR

**Comment by muhammadawaisshaikh** [comment]
> Submitted #35 PR

ok will take a look and merge it.

**Comment by muhammadawaisshaikh** [comment]
merged in production. Congratulations 🎉 🥳
