### ISSUE TITLE
Add a "Event Listing" component as a reusable component under Shared Module

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [muhammadawaisshaikh/community-events-angular#12]
![image](https://user-images.githubusercontent.com/24633059/135663406-7114af35-d129-4bc8-82e1-481560ce91fd.png)

That listing have multiple types with header like above you see in screenshot. you have to create 4 to 5 sections like this in a listing page. but please make this listing with header as a reusable component, it's mandatory, make a reusable component and call that in event listing page 4 to 5 time.

**Comment by ilyasahmedshaikh** [comment]
I want to work on this kindly please assign it to me....

**Comment by muhammadawaisshaikh** [comment]
seems good. thanks
