### ISSUE TITLE
create a "Social Share" modal as reusable component

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [muhammadawaisshaikh/community-events-angular#14]
- Create a social share modal as reusable component, and it will be opened once share button clicked from event-details component.

![image](https://user-images.githubusercontent.com/24633059/135664168-3499339b-be2f-46fa-9845-82e92aeaa7ad.png)

**Comment by kala2** [comment]
Hello, may i take this one?

**Comment by muhammadawaisshaikh** [comment]
done, merged.

**Comment by muhammadawaisshaikh** [comment]
done, merged.
