### ISSUE TITLE
create stepper tabs for "User Group" Module child components

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [muhammadawaisshaikh/community-events-angular#28]
make a stepper tabbed form work on next and previous in a good manner. see screenshot below for reference.

![image](https://user-images.githubusercontent.com/24633059/135679487-e60f5366-4cc4-47c5-bdd6-d8f84c8ecbf4.png)

**Comment by GregSithole** [comment]
Hey, here's a comment and thanks again and happy to get all 3 sorted soon

**Comment by muhammadawaisshaikh** [comment]
any update?

**Comment by GregSithole** [comment]
Hey @muhammadawaisshaikh 

With regards to the stepper, is it okay if I add a CSS Framework suited for Angular? And also do you feel the stepper component should be shared? I'm think whether you would have it again for another page in the system?
