### ISSUE TITLE
Develop content pages

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [muhammadawaisshaikh/community-events-angular#4]
- About Us (https://www.meetup.com/about/)
 - Blog (https://www.meetup.com/blog/)
 - Careers (https://www.meetup.com/careers/)

Note: please write clean component based code, pages should be developed as routed modules.

**Comment by ilyasahmedshaikh** [comment]
I want to work on this kindly please assign it to me....

**Comment by muhammadawaisshaikh** [comment]
done. thanks
